### ISSUE TITLE
Linux install instructions

### ISSUE THREAD

**Issue by dktr0** [dktr0/extramuros#10]
Probably won't work on Ubuntu 14 or 16 since nodejs-legacy and npm are not the way to install node anymore

**Comment by jwaldmann** [comment]
Just a data point: I got it working (just following your instructions) with node  v13.12.0 and npm  6.14.4. There are some warnings
```
npm install

npm WARN extramuros@0.0.3 No repository field.
npm WARN extramuros@0.0.3 No license field.

audited 759 packages in 4.845s

1 package is looking for funding
  run `npm fund` for details

found 43 vulnerabilities (22 low, 5 moderate, 16 high)
  run `npm audit fix` to fix them, or `npm audit` for details

```
but it seemed to work. I am not sure whether `--feedback` worked, though, as I've never seen how it's supposed to work, or to look like.

When I check the network log in my browser, I am seeing 
```
The resource from “http://.......:8000/jquery.min.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```
I can put a `jquery.min.js` in the server's directory, then this error goes away. Another one remains:
```
Attempt to set a forbidden header was denied: Connection bcsocket.js:45:223
```

**Comment by dktr0** [comment]
Thanks - I think we should close this issue for now anyway, since Ubuntu 14 and 16 are long gone. Feedback should show up in the extra panel that is commented out in some of the .html files but it probably hasn't been tested in a long time...
