### ISSUE TITLE
using Foxdot

### ISSUE THREAD

**Issue by ekg** [dktr0/extramuros#11]
Is there a simple way to use foxdot with extramuros? I thought it supported it, but I don't see foxdot mentioned in this repository or its issues.

**Comment by dktr0** [comment]
I would think it would be possible, but have never tried it. The key is to figure out - with any given language - what you have to do to pipe text to it. At that point, then, instructions like those given for SuperCollider in the README should probably work. If you make some progress with figuring it out - a commit/pull request explaining what to do in the README would be great!

**Comment by dktr0** [comment]
Closed by #12
